config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'login' => 'static_pages#login'

  get 'signup' => 'users#new'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	#has_secure_password
	# before save callback to downcse all emails
	# before saving to the database.
	before_save { self.email = email.downcase }
	
	# validate name
	validates :name, presence: true, length: { maximum: 49 }
	
	# validate email
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 250 },
				format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }

	# validate password
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # succcesful, redirect them!
      flash[:success] = "Registration Successful!"
      redirect_to @user
    else
      # failed
      render 'new'
    end
  end



  private
    def user_params
      params.require(:user).permit(:name,
        :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# return full title page per basis
	def full_title(page_title = '')
		base_title = "Cleaning Site"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		# return user's gravatar image
		# gravatr url based on md5 hash of user's email
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Cleaning Site by Lachlan Miller
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Contact",   help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Login", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	    <div class="container">

	    	<% flash.each do |message_type, message| %>
		    	<div class="alert alert-<%= message_type %>"><%= message %>
		    	</div>
	    	<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>

			<!--<div class="flex-container">
				<div class="flex-item">Flex 1 </div>
			</div> -->
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>

		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About MyCleaning</h1>

<p>You can put some interesting information.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<p>Contact info goes here! 連絡してください！</p>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>MyCleaning</h1>

	<h2>Personal, scalable cleaning services.</h2>

	<%= link_to "Contact Us Now!", help_path, class: "btn btn-lg btn-primary" %>
</div>

<div class="container">

	<h3>What is MyCleaning?</h3>
	<table class="table" >
		<tr align="center">
			<td><%= image_tag("flexible.png", :size => "100x100") %></td>
			<td><%= image_tag("scale.png", :size => "100x100") %></td>
			<td><%= image_tag("value.png", :size => "100x100") %></td>
		</tr>

		<tr class="table-head" align="center">
		    <td>Flexible</td>
		    <td>Scale</td>
		    <td>Value</td>
	  	</tr>
	  	
	  	<tr align="center">
		    <td class="col-md-3">
		    	Whether it's on a regular basis, daily or weekly, or just every now and then, we can arrange for care and uptake of your property.
		    </td>
	    
	    	<td class="col-md-3">
	    		From a single room to an entire house,we can clean, wash and make it look how guests expect it to.
	    	</td>
	    	<td class="col-md-3">
	    		We have cleaners who work on a casual and full time basis, and varying levels of service, so we can provide thebest package for your needs.
	    	</td>
	 	</tr>
	</table>
</div>

<div class="whitespace"></div>

<div class="container">

	<h3>How does it work?</h3>
	<h4>You provide us with some simple details, about what kind of room or property you need cleaning or maintaining, and we get back to you with the approximate costs.</h4>
	<table class="table" >
		<tr align="center">
			<td><%= image_tag("order.png", :size => "100x100") %></td>
			<td><%= image_tag("discuss.png", :size => "100x100") %></td>
			<td><%= image_tag("clean.png", :size => "100x100") %></td>
		</tr>

		<tr class="table-head" align="center">
		    <td>Order</td>
		    <td>Discuss</td>
		    <td>Cleaning</td>
	  	</tr>
	  	
	  	<tr align="center">
		    <td class="col-md-3">
		    	Send us details about the job you would like done; how many rooms, how frequently, location.
		    </td>
	    
	    	<td class="col-md-3">
	    		A member of our team will get back to as soon as possible with approximate pricing and follow up on any necessary information.
	    	</td>
	    	<td class="col-md-3">
	    		Once the details have been sorted out, the cleaning service begins! Changes and additional requests can be made at any time.
	    	</td>
	 	</tr>
	</table>
</div>

<div class="container" align="center">
	<%= link_to "Contact Us Now!", help_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3" >
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.text_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.submit "Create my account", class: "btn btn-primary" %>

		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>